
import java.awt.Component;
import java.util.HashSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ruan
 */
public class telaInicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaInicial
     */
    private EstoqueApp estoqueRef;

    public telaInicial() {
        initComponents();
    }
    
    public void setEstoqueRef(EstoqueApp estoqueRef) {
        this.estoqueRef = estoqueRef;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        adicionarButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Preço", "Descrição"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        adicionarButton.setText("Adicionar Produto");
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        atualizarButton.setText("Atualizar Produto");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        btApagar.setText("Apagar Produto");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(adicionarButton)
                .addGap(37, 37, 37)
                .addComponent(atualizarButton)
                .addGap(53, 53, 53)
                .addComponent(btApagar)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarButton)
                    .addComponent(adicionarButton)
                    .addComponent(btApagar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        // TODO add your handling code here:
        
        cadstroProduto telaAdicionarProduto = new cadstroProduto();
        telaAdicionarProduto.setTelaInicialRef(this);

        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(telaAdicionarProduto);
        telaAdicionarProduto.setVisible(true);
    }//GEN-LAST:event_adicionarButtonActionPerformed

    public void addProdutoEstoque(Produto produto) {
        estoqueRef.addProdutoEstoque(produto);
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{produto.getNome(), produto.getQuantidade(), produto.getPreco(), produto.getDescricao()});
    }
    
    public void atualizarProdutoEstoque(Produto prd, int index){
        estoqueRef.atualizarProduto(prd, index);
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int rowCount = model.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            if (i == index) {
                model.setValueAt(prd.getNome(), i, 0);
                model.setValueAt(prd.getQuantidade(), i, 1);
                model.setValueAt(prd.getPreco(), i, 2);
                model.setValueAt(prd.getDescricao(), i, 3);
                break;
            }
        }                  

    }
    
    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = jTable.getSelectedRow();
            if (selectedRow >= 0) {
                Produto produto = estoqueRef.getProdutoEstoque(selectedRow);
                
                cadstroProduto telaAdicionarProduto = new cadstroProduto(produto, selectedRow);
                telaAdicionarProduto.setTelaInicialRef(this);
                
                
                JDesktopPane desktopPane = getDesktopPane();
                desktopPane.add(telaAdicionarProduto);
                telaAdicionarProduto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(estoqueRef, "Selecione um produto para atualizar.", "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int selectedRow = jTable.getSelectedRow();
            if (selectedRow >= 0) {
                estoqueRef.apagarProdutoEstoque(selectedRow);
                model.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(estoqueRef, "Selecione um produto para Apagar.", "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton btApagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
